/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.jchankchan

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    sub(args)
}

private fun sub(args: Array<String>) {
    println(App().greeting)
    if (args.size == 0) {
        println("Please provide a name as a command-line argument")
        return
    }
    args.forEachIndexed { index, s -> println("args[${index}]: "+ s) }
}